### ISSUE TITLE
From passkit-generator: splice not working on FieldsArray

### ISSUE THREAD

**Issue by alexandercerutti** [zhenwenc/sandbox-viper#1]
Hello there! As I always look at who is using my library (and how it gets used), I saw this comment of yours:

https://github.com/zhenwenc/sandbox-viper/blob/7c4c51d88d63bdf337c377fecdc0c8ab4c0e1d30/server/applepass/service.ts#L91

I can confirm that FieldsArray contains overridden Array methods. In v2 `Array.prototype.splice` wasn't overridden, while in v3 it is overridden. I suggest you move to v3 by following also the Migration Guide I created!

Hope this is helpful. 😊
Thanks for using passkit-generator!

**Comment by zhenwenc** [comment]
Hi @alexandercerutti, thank you very much for the info! This is very helpful. The initial intention of using `splice` was trying to avoid mutating the `Field#value`. Keen to migrate to v3.

There is another question, I noticed when setting the expiration date for a pass, the library is assembling a **W3C date/time in UTC timezone** with methods like `Date#getDate`, `Date#getHours`, etc, which returns **values in the machines local timezone**. 

https://github.com/alexandercerutti/passkit-generator/blob/ccd38262ec69d37b669774aba6812feeb0a16534/src/utils.ts#L24-L63

This might be okay since servers are usually configured to use UTC timezone, but could potentially cause issues. I was noticed this in a unit test, it produces a different result from my local and CI pipeline.

Many thanks for building the awesome passkit-generator library! Honestly, I am very impressed by its quality and the detailed documentation! 👍

**Comment by alexandercerutti** [comment]
W3CDate is [the required format by Apple](https://developer.apple.com/documentation/walletpasses/pass) for relevantDate and, even if it is not written there but it is written in [the archived version](https://developer.apple.com/library/archive/documentation/UserExperience/Reference/PassKit_Bundle/Chapters/TopLevel.html#//apple_ref/doc/uid/TP40012026-CH2-SW1), for expirationDate. Maybe we could discuss it there (in a discussion topic), so we might find a way to improve things and not repeat things again and again in every implementation. 😄

Thank you very much! Documentation and quality were my main focus. I wanted to share with others the more knowledge I could, 'cause before Passkit-Generator was born, Apple Documentation was worse than the current one. The current one still misses a lot of things IMHO.

May I ask you to leave a star on the project? I think that stars ⭐️ on Github help a lot to "spread the word", so if you could give one to it, that would be great! 🌟

**Comment by zhenwenc** [comment]
Thanks for the detailed explanation. 👍 Sure thing! More than happy to star the project. Great work! 🌟
